# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wh.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WH(object):
    def setupUi(self, WH):
        WH.setObjectName("WH")
        WH.resize(1054, 705)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(WH)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(WH)
        self.label.setStyleSheet("font: 14pt \"新宋体\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_browser = QtWidgets.QLineEdit(WH)
        self.lineEdit_browser.setStyleSheet("font: 14pt \"Courier New\";")
        self.lineEdit_browser.setObjectName("lineEdit_browser")
        self.horizontalLayout_2.addWidget(self.lineEdit_browser)
        self.btn_brsw = QtWidgets.QPushButton(WH)
        self.btn_brsw.setStyleSheet("font: 14pt \"新宋体\";")
        self.btn_brsw.setObjectName("btn_brsw")
        self.horizontalLayout_2.addWidget(self.btn_brsw)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(WH)
        self.label_2.setStyleSheet("font: 14pt \"新宋体\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cbx_months = QtWidgets.QComboBox(WH)
        self.cbx_months.setStyleSheet("font: 14pt \"Courier New\";")
        self.cbx_months.setObjectName("cbx_months")
        self.horizontalLayout_3.addWidget(self.cbx_months)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_run = QtWidgets.QPushButton(WH)
        self.btn_run.setStyleSheet("font: 14pt \"新宋体\";")
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout_4.addWidget(self.btn_run)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(WH)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(WH)
        self.label_4.setStyleSheet("font: 14pt \"新宋体\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_group = QtWidgets.QLabel(WH)
        self.label_group.setStyleSheet("font: 14pt \"新宋体\";\n"
"color: rgb(24, 74, 255);")
        self.label_group.setObjectName("label_group")
        self.horizontalLayout.addWidget(self.label_group)
        self.label_3 = QtWidgets.QLabel(WH)
        self.label_3.setStyleSheet("font: 14pt \"新宋体\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_savedata = QtWidgets.QLabel(WH)
        self.label_savedata.setStyleSheet("font: 14pt \"新宋体\";\n"
"color: rgb(255, 0, 0);")
        self.label_savedata.setObjectName("label_savedata")
        self.horizontalLayout.addWidget(self.label_savedata)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(3, 8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(WH)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(WH)
        QtCore.QMetaObject.connectSlotsByName(WH)

    def retranslateUi(self, WH):
        _translate = QtCore.QCoreApplication.translate
        WH.setWindowTitle(_translate("WH", "工时量统计助手"))
        self.label.setText(_translate("WH", "选择数据目录"))
        self.btn_brsw.setText(_translate("WH", "浏览"))
        self.label_2.setText(_translate("WH", "选择统计月份"))
        self.btn_run.setText(_translate("WH", "统计"))
        self.label_4.setText(_translate("WH", "分组:"))
        self.label_group.setText(_translate("WH", ".."))
        self.label_3.setText(_translate("WH", "数据路径:"))
        self.label_savedata.setText(_translate("WH", "...."))

